nginx_vhosts:
  - listen: "443 ssl http2"
    server_name: "cloudimix.com"
    server_name_redirect: "www.cloudimix.com"
    root: "/var/www/cloudimix.com"
    index: "index.php index.html index.htm"
    state: "present"
    template: "{{ nginx_vhost_template }}"
    filename: "cloudimix.com.conf"
    ssl: on
    ssl_certificate: /home/ubuntu/.tls/ssl-cert.crt;
    ssl_certificate_key: /home/ubuntu/.tls/ssl-cert.key;
    ssl_protocols: TLSv1.1;TLSv1.2;

    extra_parameters: |
      location ~ \.php$ {
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass unix:/var/run/php5-fpm.sock;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include fastcgi_params;
      }
      ssl_certificate     /home/ubuntu/.tls/ssl-cert.crt;
      ssl_certificate_key /home/ubuntu/.tls/ssl-cert.key;
      ssl_protocols       TLSv1.2;
      ssl_ciphers         HIGH:!aNULL:!MD5;
